### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by loicsaintroch** [extensdotio/extens.io#1]
Hey guys,

It appears some of you are encountering errors with `$ npm install extens.io -g`.
Can you please give us feedbacks about that? Do you have any idea how to fix that?

Bests,
The extens.io team.

**Comment by andyhu** [comment]
Some of the directories and files are nested to deep. Windows only supports file name less than 260 characters and the directory name should be less than 248 characters.

**Comment by loicsaintroch** [comment]
All right. I see an important issue here: very deep dependencies which shouldn't be. Which means we can improve installation process and dependencies workflow. We'll work on that this week-end. We keep you inform. Thank you for your answer @andyhu.

**Comment by andyhu** [comment]
You are most welcome. I always wanted to do something similar with sails but never have enough time and resources. It's great that you guys made a good start. It feels like io.js vs node.js in sails.js world :)

**Comment by loicsaintroch** [comment]
Yes a lot of people wanted to start something similar... Awesome thank you for your help @andyhu we appreciate! Concerning Node.js vs io.js, we'll talk about that in a few weeks.

**Comment by andyhu** [comment]
I also tried to install it on a Linux VPS, but also failed. Here is the log:
```
npm WARN engine extens.io@0.11.0: wanted: {"node":">= 0.10.35","npm":">= 2.1.0"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN deprecated node-switchback@0.0.4: The 'node-switchback' NPM module is now simply 'switchback'. See https://github.com/node-machine/switchback for latest docs.
npm WARN deprecated node-switchback@0.0.2: The 'node-switchback' NPM module is now simply 'switchback'. See https://github.com/node-machine/switchback for latest docs.
 
> kerberos@0.0.7 install /usr/lib/node_modules/extens.io/node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm WARN deprecated guid@0.0.12: Please use node-uuid instead. It is much better.
 
> bson@0.2.18 install /usr/lib/node_modules/extens.io/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
> ws@0.5.0 install /usr/lib/node_modules/extens.io/node_modules/sails-hooks/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.5.0 install /usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.4.31 install /usr/lib/node_modules/extens.io/node_modules/sails-hooks/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.5.0 install /usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-hooks/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.4.31 install /usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.5.0 install /usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.4.31 install /usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-hooks/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.4.31 install /usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> node-sass@1.0.3 install /usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/grunt-sass/node_modules/node-sass
> node build.js

`linux-x64-v8-3.14` exists; testing

  
  ?もももももももももももももももももももももももももも

  27 passing (288ms)

Binary is fine; exiting

> node-sass@1.0.3 install /usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/grunt-sass/node_modules/node-sass
> node build.js

`linux-x64-v8-3.14` exists; testing

  
  ?もももももももももももももももももももももももももも

  27 passing (132ms)

Binary is fine; exiting

> sails-generate-frontend@0.11.0 postinstall /usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend
> bower cache clean; bower install


Error: EACCES, permission denied '/root/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Error: EACCES, permission denied '/root/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/lib/node_modules/extens.io/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

> sails-generate-frontend@0.11.0 postinstall /usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend
> bower cache clean; bower install


Error: EACCES, permission denied '/root/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Error: EACCES, permission denied '/root/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/lib/node_modules/extens.io/node_modules/sails-admin/node_modules/sails-generate/node_modules/sails-generate-frontend/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! EEXIST, open '/root/.npm/0e38d45e--npm-express-3-16-10-package-tgz.lock'
File exists: /root/.npm/0e38d45e--npm-express-3-16-10-package-tgz.lock
Move it away, and try again. 
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "-g" "i" "extens.io"
npm ERR! cwd /root
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path /root/.npm/0e38d45e--npm-express-3-16-10-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

**Comment by loicsaintroch** [comment]
It's because of permissions. `bower install` can't work with `sudo`. But a lot of users can't install a node module globally without `sudo`. So the deal is: do we keep the `bower install` script and ignore assets on Git or remove this script and keep everything on Git. What do you think?

**Comment by andyhu** [comment]
How about making the core files a bit more cleaner, and give all sails-generate-* tasks to something like `yo` like MEAN.js?

**Comment by loicsaintroch** [comment]
The core is clean on this, every scripts are in generators.

**Comment by loicsaintroch** [comment]
We worked around dependencies and the installation process today. Can you try to install the new version @andyhu please?

```bash
$ [sudo] npm uninstall extens.io -g
$ [sudo] npm cache clear
$ npm install extens.io -g
```

You can verify the installation with `$ extensio -v`.

**Comment by andyhu** [comment]
There is still one error on windows because of the file name is too long:
```
 [C:\Users\Andy\AppData\Roaming\npm\node_modules\extens.io\node_modules\sails-h
ooks\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\socket
.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxpr
oj]
```
However the installation process is completed even with some incompelete modules.

**Comment by loicsaintroch** [comment]
Interesting... I think it should work if we add `socket.io-client` as a dependency of `sails-hook-sockets` aiming to avoid the deep dependencies with `engine.io-client` and `ws`.

**Comment by hack1337** [comment]
What's your windows version ? I don't have this problem with Windows 8

**Comment by loicsaintroch** [comment]
I just wrote a pull request on `sails-hook-sockets`. It should fix it.

**Comment by andyhu** [comment]
@hack1337 It's Windows 7 32bit with `-g` option

**Comment by andyhu** [comment]
Just tested again, now I can install it without any errors. Thanks @loicsaintroch @hack1337 for the awesome work! Will play around it a bit and probably use it in my next project.
Also where do you think is the right place for project related discussions? Like thoughts and feature requests etc.. Recently I have done a bit of work in making waterline adapters for TingoDB and an a whole rewrite for NeDB adapter (since it's not working correctly and have serious bugs). I also found a few issues with sails-mongo, some are functional errors and some will greatly hurt performance. But it seems that sails team isn't very keen to accept new PRs even it's fatal, which reminds me a bit of node.js vs io.js story. If you guys are happy I'm willing to fix a few things I know in sails in your forked version

**Comment by loicsaintroch** [comment]
> Just tested again, now I can install it without any errors. Thanks @loicsaintroch @hack1337 for the awesome work! Will play around it a bit and probably use it in my next project.

Sure, please give us some feedbacks when you want!

> Also where do you think is the right place for project related discussions? Like thoughts and feature requests etc..

extens.io is an open-source governance project. Our goal for the week-end is to write guides about how to contribute, the GitHub workflow and the governance. So, we stay in touch.

> But it seems that sails team isn't very keen to accept new PRs even it's fatal, which reminds me a bit of node.js vs io.js story.

Indeed. This is exactly why we decided to fork Sails and create a whole open governance around it.

> If you guys are happy I'm willing to fix a few things I know in sails in your forked version

Waouh! That would be awesome. Thank you for your help @andyhu we really appreciate.

**Comment by hack1337** [comment]
@andyhu so cool ! Your feedback will be very interesting for us !

**Comment by andyhu** [comment]
```
error: Grunt :: An error occurred.
error: Aborted due to warnings.
Running "sass:dev" (sass) task
Warning: l:/Source/extensio/theme/assets/styles/importer.scss:1: file to import
not found or unreadable: 'normalize'
Current dir: l:/Source/extensio/theme/assets/styles/

error: Looks like a Grunt error occurred!
error: Please fix it, then restart the Sails framework to continue running tasks
.
error: Or if you're stuck, check out the troubleshooting tips below.
error: Troubleshooting tips:
error:  -> Are `grunt` and related Grunt task modules installed locally?  Run `n
pm install` if you're not sure.
error:  -> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error:  -> Or maybe you don't have permissions to access the `.tmp` directory?
error:      If you think this might be the case, try running:
error:      `$ sudo chown -R YOUR_COMPUTER_USER_NAME l:\Source\extensio\.tmp `
```
After installation, I used `extens.io new myApp` to generate the site, then when starting the server I saw the above errors

**Comment by loicsaintroch** [comment]
It's a weird issue. Sometimes it appears, sometimes it doesn't.

**Comment by loicsaintroch** [comment]
I close this issue since every installation issues are solved and we don't take care of the front-end anymore. We'll release the v11.0.3 in the next few days.
